# Ask TravisCI to build the site for testing purposes,
# results at https://travis-ci.org/peterjc/peterjc.github.io/builds
# See https://help.github.com/articles/troubleshooting-github-pages-build-failures/

language: ruby
script: "bundle exec jekyll build"
